### ISSUE TITLE
`fit_jara()` obscure error when few data

### ISSUE THREAD

**Issue by AMBarbosa** [Henning-Winker/JARA#12]
An obscure error message is returned sometimes which might have to do with insufficient data, but it is hard to figure out. Example:

```
dat <- data.frame(year = 2012:2022, abundance = c(710, 243, 584, 455, 735, 705, 543, 548, 455, 536, 310))
```

All is fine if I use all 11 years/rows, and even down to just the first 6 years/rows. However, if I try with just the first 5 rows, `fit_jara()` then returns an obscure error message that is hard for users to debug:

```
jr <- build_jara(dat[1:5, ])
set.seed(1)
fit_jara(jr)
# Error in apply(posteriors$r[, (n.years - round(GL, 0)):(n.years)], 1,  : 
#  dim(X) must have a positive length
```

A more informative error message would be useful. Cheers!

**Comment by rbsherley** [comment]
You should really specify the generation length for your species. If you don't, JARA assumes it to be n.data/3 and that you've given it a dataset long enough to calculate a decline over 3 GL (since that is what it is designed to do). JARA needs 3 data points around which to calculate the starting population for the decline, then enough data for 3 GL after that, so essentially you haven't given it enough data to do this and this results in build_jara calculating a GL of 0 years  - if you look at what is returned in the console by build_jara, it would have been saying "Assuming a Generation length of GL = 0 years". I've added an warning, but really it is best to use JARA with the GL argument supplied.

**Comment by AMBarbosa** [comment]
Thanks! I'm aware of the GL argument for `build_jara()`, and I totally agree it should generally be specified explicitly. But users (and students) often don't do as they should, and the `?build_jara` help file says the default GL is n.years/3, which does not seem to be the case. In the above example, the user could be expecting the function to use GL=5/3 (which would actually work if supplied explicitly), run `build_jara()` with `silent=TRUE` (therefore not seeing the "_Assuming a Generation length of GL = 0 years_"), and then get stuck at a puzzling error message. The new warning helps indeed, but I think the `?build_jara` help file should say that the default GL is actually `floor(n.years-3)/3)` (as I see from the function code and whose reason becomes clear with your explanation above). Regards!

**Comment by rbsherley** [comment]
Yes, good point! I'll update the help file.
